#ifndef FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H
#define FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H

#include "../datax_core/global.h"

#ifdef FOUG_DATAX_LIBSTL_DLL
# ifdef FOUG_DATAX_LIBSTL_MAKE_DLL
#  define FOUG_DATAX_LIBSTL_EXPORT FOUG_DECL_EXPORT
# else
#  define FOUG_DATAX_LIBSTL_EXPORT FOUG_DECL_IMPORT
# endif /* FOUG_DATAX_LIBSTL_MAKE_DLL */
#else
# define FOUG_DATAX_LIBSTL_EXPORT
#endif /* FOUG_DATAX_LIBSTL_DLL */

/* STLB */
#define FOUG_STLB_HEADER_SIZE 80
#define FOUG_STLB_MIN_CONTENTS_SIZE 284

#endif /* FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H */
