/****************************************************************************
** gmio
** Copyright Fougue (2 Mar. 2015)
** contact@fougsys.fr
**
** This software is a reusable library whose purpose is to provide complete
** I/O support for various CAD file formats (eg. STL)
**
** This software is governed by the CeCILL-B license under French law and
** abiding by the rules of distribution of free software.  You can  use,
** modify and/ or redistribute the software under the terms of the CeCILL-B
** license as circulated by CEA, CNRS and INRIA at the following URL
** "http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html".
****************************************************************************/

/* Generated by CMake */

#ifndef GMIO_VERSION_H_CMAKE
#define GMIO_VERSION_H_CMAKE

#  define GMIO_VERSION_MAJOR  @GMIO_VERSION_MAJOR@
#  define GMIO_VERSION_MINOR  @GMIO_VERSION_MINOR@
#  define GMIO_VERSION_PATCH  @GMIO_VERSION_PATCH@
#  define GMIO_VERSION_STR    "@GMIO_VERSION@"
#  define GMIO_VERSION        0x0@GMIO_VERSION_MAJOR@0@GMIO_VERSION_MINOR@0@GMIO_VERSION_PATCH@

#endif /* GMIO_VERSION_H_CMAKE */
