#ifndef FOUG_C_SUPPORT_GLOBAL_H
#define FOUG_C_SUPPORT_GLOBAL_H

#include <datax_core/global.h>

#ifdef FOUG_LIBSUPPORT_DLL
# ifdef FOUG_LIBSUPPORT_MAKE_DLL
#  define FOUG_LIBSUPPORT_EXPORT FOUG_DECL_EXPORT
# else
#  define FOUG_LIBSUPPORT_EXPORT FOUG_DECL_IMPORT
# endif /* FOUG_LIBSUPPORT_MAKE_DLL */
#else
# define FOUG_LIBSUPPORT_EXPORT
#endif /* FOUG_LIBSUPPORT_DLL */

#endif /* FOUG_C_SUPPORT_GLOBAL_H */
