#ifndef FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H
#define FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H

#include "../global.h"

#ifdef FOUG_DATAX_LIBSTL_DLL
# ifdef FOUG_DATAX_LIBSTL_MAKE_DLL
#  define FOUG_DATAX_LIBSTL_EXPORT FOUG_DECL_EXPORT
# else
#  define FOUG_DATAX_LIBSTL_EXPORT FOUG_DECL_IMPORT
# endif /* FOUG_DATAX_LIBSTL_MAKE_DLL */
#else
# define FOUG_DATAX_LIBSTL_EXPORT
#endif /* FOUG_DATAX_LIBSTL_DLL */

/* STLB */
#define FOUG_STLB_HEADER_SIZE 80
#define FOUG_STLB_MIN_CONTENTS_SIZE 284
#define FOUG_STLB_TRIANGLE_SIZE 50 /* 12 * sizeof(foug_real32_t) + sizeof(uint16_t) */

#endif /* FOUG_DATAX_C_LIBSTL_STLB_GLOBAL_H */
