/* Generated by CMake */

#ifndef FOUG_CONFIG_H_CMAKE
#define FOUG_CONFIG_H_CMAKE

#ifndef FOUG_HAVE_STDINT_H
#cmakedefine FOUG_HAVE_STDINT_H
#endif /* FOUG_HAVE_STDINT_H */

#endif /* FOUG_CONFIG_H_CMAKE */
